### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Stixz** [blaxxun-boop/TargetPortal#1]
I have the option to change the mode for the portals, I walk into the portal the map opens, I try left-clicking on the portal and nothing happens. These are portals I had in my game prior to this mod, do they need to be built after the mod had been installed?

**Comment by blaxxun-boop** [comment]
Sounds like you are using a mod that prevents you from clicking on the map. Feel free to share your mod list and I'll have a look.

And no, you don't have to rebuild your portals for this to work.

**Comment by Stixz** [comment]
Yeah? I kinda thought that also, but I couldn't see one that would do that, then again, I don't write mods. :)

Here is my mod list, note that some are disabled. (Auga, BoneAppetit, Stronghold, TargetPortal). I disabled this one as it wasn't working and I couldn't use my portals.
[ChaXe_1650049697948.zip](https://github.com/blaxxun-boop/TargetPortal/files/8497874/ChaXe_1650049697948.zip)

**Comment by blaxxun-boop** [comment]
Not sure what I am supposed to do with the file you've uploaded. Tried to import it in R2, but that doesn't work.

**Comment by Stixz** [comment]
It's an export via Thunderstore MM. If you extract it first it should import. It's the easiest and quickest way I know to do a list, without typing out all the mods.? I suppose I can just attach some SS.

![Screenshot 2022-04-16 112253](https://user-images.githubusercontent.com/37002867/163680785-74076114-42ca-43be-99d0-71502e1ea18d.png)
![Screenshot 2022-04-16 112329](https://user-images.githubusercontent.com/37002867/163680786-2c1886ba-36af-48df-92cf-407306ee5052.png)
![Screenshot 2022-04-16 112407](https://user-images.githubusercontent.com/37002867/163680787-f1139bb2-2e7d-4cd7-9b59-7d3429fa46b7.png)

**Comment by blaxxun-boop** [comment]
Yeah, but importing this to R2 doesn't work, as I said.

I'd probably start by disabling AutoMapPins and check, if that fixes the issue.

**Comment by Stixz** [comment]
I appreciate you trying to help me.

I created a new profile, only installed TargetPortal and BeInExPack, loaded a different map and it still doesn't work. BTW: I am using the same character from my main profile/map. No, I don't have any items on the char. that aren't allowed to be teleported. Game ver. is 0.208.1. :(

**Comment by blaxxun-boop** [comment]
Are you playing with a game pad instead of a mouse, by any chance?

**Comment by Stixz** [comment]
No, mouse and KB.

**Comment by Bucketsmith** [comment]
Having the same problem.
![image](https://user-images.githubusercontent.com/20886583/164244452-acb81519-2604-4a3f-ac5a-5c897b800765.png)
![image](https://user-images.githubusercontent.com/20886583/164244534-185d323c-98f0-4c64-994a-2bff2ba0292e.png)
![image](https://user-images.githubusercontent.com/20886583/164244592-265db726-1eec-422d-a953-7b5d124a5cb9.png)
![image](https://user-images.githubusercontent.com/20886583/164244664-131d5082-b05e-4ca5-bbd6-664aa2365ad6.png)
![image](https://user-images.githubusercontent.com/20886583/164244746-3f69aef2-e4c5-4257-88bd-202ca9b0aa43.png)
![image](https://user-images.githubusercontent.com/20886583/164244809-1cf55bd2-858f-4d7e-9cb1-313b84cb4dd9.png)
![image](https://user-images.githubusercontent.com/20886583/164244897-252e58e8-d386-411a-ba5a-0a46f3bc1361.png)
![image](https://user-images.githubusercontent.com/20886583/164244948-35c15b63-c8c2-4d36-9921-e0f952c7e63e.png)

**Comment by virtualbjorn** [comment]
I know this isn't relevant but you can copy the whole mod list just by going to `Settings > Modpacks`
![image](https://user-images.githubusercontent.com/19782129/170858942-42a2a8d8-02e7-4fa1-89c2-9ccc4ff1e367.png)

which will then give you 
![image](https://user-images.githubusercontent.com/19782129/170858962-0d41bc03-52ec-4bfd-9863-33c92f8b894b.png)

**Comment by Bucketsmith** [comment]
> I know this isn't relevant but you can copy the whole mod list just by going to `Settings > Modpacks`

Does that only work with modpacks tho?

**Comment by virtualbjorn** [comment]
It works even without a modpack

**Comment by Bucketsmith** [comment]
Thanks man!

**Comment by Stixz** [comment]
@virtualbjorn That's a good piece of info. to have. Thanks!

**Comment by kohanis** [comment]
For me it's AlweStats. And, yes, It modifies save for some reason
