### ISSUE TITLE
Having hammer equipped prevents teleporting.

### ISSUE THREAD

**Issue by AgentX2006** [blaxxun-boop/TargetPortal#14]
If you have the hammer equipped you get the an item prevents you from teleporting message. It is not readily apparent that this is the cause. I ended up triple checking my inventory for ingots and ore.
![image](https://user-images.githubusercontent.com/51245403/210201056-618062cc-60d0-46be-a30e-15c896cf8392.png)

**Comment by blaxxun-boop** [comment]
Tested, works fine.
