### ISSUE TITLE
Entering portal with inventory open prevents interaction with map

### ISSUE THREAD

**Issue by AgentX2006** [blaxxun-boop/TargetPortal#15]
Entering a portal with the inventory open prevents interaction with map as while they are both open the inventory has priority and only it can be interacted with. You also can't close the inventory while they are both open requiring you to step out of the portal which closes the map. Possible fix would be to force close the inventory if it's open before opening the map.
![image](https://user-images.githubusercontent.com/51245403/210201568-e5bd3400-40f2-4ad8-bae1-e29b3911ecdc.png)

**Comment by blaxxun-boop** [comment]
Fixed in v1.1.7 now, thanks to probablykory.
