### ISSUE TITLE
Feature Request: Add compatibility with AdvancedPortals

### ISSUE THREAD

**Issue by LongParsnip** [blaxxun-boop/TargetPortal#16]
https://valheim.thunderstore.io/package/RandyKnapp/AdvancedPortals/

It looks like this mod is doing the restriction checks when you attempt to teleport, if possible can you add compatibility with this brand new mod.

Cheers.

**Comment by blaxxun-boop** [comment]
No. Just use the original, which just works fine with all other portal mods.
https://valheim.thunderstore.io/package/WackyMole/RareMagicPortal/
