### ISSUE TITLE
Logging in and out on an online server breaks portals

### ISSUE THREAD

**Issue by MontyLFP** [blaxxun-boop/TargetPortal#2]
Portals seem to disappear when logging in and out in online games. One portal remained upon logging in and out, but all other portals disappeared, rendering fast travel impossible unless someone was able to destroy and recreate the portal at the other end. Other players who have not logged out were able to view and use portals properly.

The server and clients had the same mod configuration given via Thunderstore code oUZPmqFZqR

![unknown](https://user-images.githubusercontent.com/7494262/163519935-07d98fa2-3a97-44d0-a4d0-c1ff2e5ef9f0.png)
![20220415003924_1](https://user-images.githubusercontent.com/7494262/163519941-95a9b204-fc05-4215-92dc-b498ac481293.jpg)

**Comment by AzumattDev** [comment]
This is likely BetterNetworking doing this. It's, in fact, not "better" and causes issues.

Blaxxun, just so you don't have to download his profile. Here are the mods he is running.

denikson-BepInExPack_Valheim-5.4.1900
ValheimPlus-ValheimPlus-9.9.8
RandyKnapp-ExtendedItemDataFramework-1.0.7
RandyKnapp-EpicLoot-0.8.8
CW_Jesse-BetterNetworking_Valheim-1.2.201
JereKuusela-Smoke_Collision-1.0.0
cjayride-InstantMonsterLootDrop-0.4.0
OdinPlus-BasementJVLedition-1.0.9
Advize-PlantEverything-1.10.1
cjayride-Discard_or_Recycle_Inventory_Items_No_Coins_cjaycraft_fix-1.3.4
Smoothbrain-TargetPortal-1.1.0

**Comment by MontyLFP** [comment]
Our fault, and sorry for the lazy report. We'll remove that mod and check again later.

**Comment by MontyLFP** [comment]
It was  CW_Jesse-BetterNetworking_Valheim-1.2.201.
