### ISSUE TITLE
Seems to be broken after the update

### ISSUE THREAD

**Issue by MasterChef5311** [blaxxun-boop/TargetPortal#20]
was working, then my buddy joined and he had updated so it didnt work for him, then i updated thinking it was a mis match but now doesent work for me too

**Comment by blaxxun-boop** [comment]
Sounds like you have Valheim Plus installed. None of my mods will work with Valheim Plus.

For more info see https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by evilHarry64** [comment]
I have valheim plus installed and the version 1.1.6 does work with valheim plus... at least I had no problems.
I have now reverted to 1.1.6 and the portals work again.

**Comment by blaxxun-boop** [comment]
Yes, this is on purpose. As I said, moving forward none of my mods will work with Valheim Plus.
