### ISSUE TITLE
Incompatible with Valheim Plus

### ISSUE THREAD

**Issue by Ageous27** [blaxxun-boop/TargetPortal#21]
The original Valheim Plus has been abandoned and through the Discord a new dev has started supporting a fork.  With Valheim Plus 9.9.11 and Target Portal 1.1.6 and before game patch v0.207.20 they worked fine together.  Now with Valheim Plus 9.9.15 (https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.9.15) and Target Porta 1.1.7 I get this error.

[Error  :   BepInEx] Could not load [TargetPortal 1.1.7] because it is incompatible with: org.bepinex.plugins.valheim_plus

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose. None of my mods work with Valheim Plus. A lot of other modders are doing the same and more and more join in. Valheim Plus is a terrible mod and needs to go.

For more info check https://github.com/blaxxun-boop/PassivePowers/issues/5
