### ISSUE TITLE
Valheim+ Compat

### ISSUE THREAD

**Issue by drekbad** [blaxxun-boop/TargetPortal#22]
Hello! Love all of your mods, and was hoping to be able to leverage this portal mod as well as Building, Farming and Foraging, however each one errors with incompatibility against the current version of Valheim+. I couldn't get them showing/working in game, but with those mods on client + server, the game loads fine anyway. Is it a mistake? Several other of your mods (mostly the skill mods) work fine with the current V+. Thank you!

**Comment by blaxxun-boop** [comment]
That is on purpose. Moving forward, all of my mods will be incompatible with Valheim Plus. A lot of modders are doing the same already and more and more are joining in. Valheim Plus is a terrible mod and needs to go.
While I don't update my mods just to add the incompatibility, if I happen to update the mod anyway, I will add it to my other mods as well.

For more info see https://github.com/blaxxun-boop/PassivePowers/issues/5
