### ISSUE TITLE
Incompatibility with Network

### ISSUE THREAD

**Issue by Thaumatarge** [blaxxun-boop/TargetPortal#3]
Seeing an already solved issue, I have noticed that the same problem happens with your very own Network mod. For some reason when one tampers with network limits, portals just don't do what they are supposed to do. 

When I tested it with my friend, the portal at our base simply just did not exist for him until I rebuilt it, most likely explaining why he didn't see any other portal in the world. I have no idea what causes these problems exactly, but it seems it has something to do with network limits or how this portal mod interacts with network limits. 

I am reporting it here, because we did not experience any other issues with the Network mod and we also did not experience any portal issues before installing this mod, as well as we do not experience any issues with the mod without the Network mod.

The reason why I installed the Network mod is because we have a lot of mods and experience with weird desync issues that I believe were caused by the network limits trying to cope with a lot of mods.

**Comment by blaxxun-boop** [comment]
I've added a ZDO buffer, which should prevent portals from disappearing, if another mod delays the sending of ZDOs.
