### ISSUE TITLE
Server Version bumped to 0.217.38

### ISSUE THREAD

**Issue by martindemharter** [blaxxun-boop/TargetPortal#31]
Hi,

first of all, thanks for your amazing work.

Unfortunately the server client on EA branch of Valheim was bumped to 0.217.38 (yule and bug fixing) and now we are stranded in a world without proper working teleporter.
I fried to fiddle arround to get it running, but no avail. Could you please bump the version to include 0.217.38 as well? 

Thanks in advance!

Martin

**Comment by blaxxun-boop** [comment]
The mod works perfectly fine on 0.217.38. You probably have another mod that breaks it.
