### ISSUE TITLE
Incompatible with Valheim Plus

### ISSUE THREAD

**Issue by traffensperger** [blaxxun-boop/TargetPortal#32]
TargetPortal refuses to load due to its incompatibility with Valheim Plus. `[Error  :   BepInEx] Could not load [TargetPortal 1.1.16] because it is incompatible with: org.bepinex.plugins.valheim_plus`

Any plans to debug and potentially fix this?

**Comment by blaxxun-boop** [comment]
https://github.com/blaxxun-boop/PassivePowers/issues/5
