### ISSUE TITLE
TargetPortal 1.1.16 not working with Valheim Patch 0.217.46

### ISSUE THREAD

**Issue by NMHBelanna** [blaxxun-boop/TargetPortal#37]
@blaxxun-boop 
Like the previous issue stated, TargetPortal isn't working with the latest patch. We're able to step into the portal and it pulls up the map, but we're unable to click on any portals. I'm running a dedicated server with 20+ players, and since it wasn't immediately obvious that the mod was broken, everyone got the new profile code and came back to play, only to find out they were stuck. This is the only mod we have left that needs fixed (that we're aware of). 

I've added an image one of my players took of the error that gets thrown when trying to click on a portal.

![image](https://github.com/blaxxun-boop/TargetPortal/assets/166926467/a30262ba-b384-4b19-9724-34a184f4ad4a)

It also appears that someone has created a fix for the issue, but I haven't yet modified any dll files and would rather not try to rig it just yet. https://github.com/blaxxun-boop/TargetPortal/pull/35/files

Please fix this issue, as we started our world with this mod in place, so our portals are mostly unnamed and not designed for vanilla portals.

**Comment by brunogenovese** [comment]
+1, same issue here.  

Disabling the mod and using vanilla portals works, but that is not the desired effect.   

Also hoping for a fix soon, or recommendations for another mod that performs the same "choose your portal from the map" function.

**Comment by NMHBelanna** [comment]
Thanks Blax!
