### ISSUE TITLE
[Ashlands Beta] Does not allow portaling with metal/ore using the new Stone Portals 

### ISSUE THREAD

**Issue by bsltx-github** [blaxxun-boop/TargetPortal#39]
When entering the new Stone Portal and trying to target another Stone Portal, you still get the error about having something in your inventory that cannot be teleported.

**Comment by blaxxun-boop** [comment]
Please do not report bugs from the PTB. You shouldn't even be playing modded on the PTB. Even Iron Gate asks you not to. Just causes more work for the Valheim devs AND the mod authors. The PTB is meant to test vanilla for bugs.
