### ISSUE TITLE
Completely broken with the hotfix today!

### ISSUE THREAD

**Issue by DiahsREAL** [blaxxun-boop/TargetPortal#46]
Only portals that load in are the ones that are directly loaded in to your area and spawn, everything else is unloaded, you can unlock them again by flying over and loading them in again but once you log out and log back in it completely breaks again. This makes this mod unusable, I love this mod I hope for hotfix soon!

**Comment by blaxxun-boop** [comment]
Usually caused by BetterNetworking.

**Comment by DiahsREAL** [comment]
Better networking isn’t on my server or my modpack so it cannot be ther
