### ISSUE TITLE
Still broken on multiplayer servers.

### ISSUE THREAD

**Issue by DiahsREAL** [blaxxun-boop/TargetPortal#47]
Hello again, exact same problem, you said it was BetterNetworking however I have never heard of that mod in my life until you brought it up so it is not that. I will give a detailed account of my mods to help you better understand. The portals are only working in loaded areas such as spawn or where you are located. 
Mods:
BepInExPack_Valheim
PlantEverything
EquipmentAndQuickSlots
TeleportEverything
Sailing
Farming
OdinHorse
AutoRepair
UseEquipmentInWater
Mining
Foraging
Just_Keep_My_Skills_Please
CraftFromContainers
NoRainDamage
InfiniteTorches
TargetPortal
PassivePowers
Tenacity
PackHorse
Vitality
Jotunn
VitalityFix
Evasion
Exploration
BetterLaddersContinued
BetterRiding
Quick_Stack_Store_Sort_Trash_Restock
DarwinAwards
Building
Lumberjacking
SteadyRegeneration
Chain_Manager
SeedBed
JustNoRoof
Server_devcommands

As you can see I am NOT using the mod you assumed I was using, if I could get back helpful feedback or a fix that would be wonderful. This has ONLY started happening yesterday with the new Valheim hotfix they released. Before this the mod was working perfectly but completely and utterly broke with the new patch being "Patch 0.218.21"

**Comment by blaxxun-boop** [comment]
Please stop creating issues for this. It's not caused by TargetPortal and I am unable to help you with this. Just disable other mods until it works.
