### ISSUE TITLE
Public/Private Setting

### ISSUE THREAD

**Issue by cosmicc** [blaxxun-boop/TargetPortal#5]
Its preventing portal non-owners to change portal settings, but it looks like it lets non-owners set portal mode to private.

Is there anyway to prevent this to only owners? Or am I doing something wrong?

**Comment by blaxxun-boop** [comment]
Not sure what your question is, sorry.
There is no setting to prevent non-owners from changing the portal mode, because it wouldn't make any sense. You could just destroy and rebuild the portal anyway.
The last person to change the portal mode of a portal becomes the owner of that portal.
