### ISSUE TITLE
Portals stop showing on map!

### ISSUE THREAD

**Issue by Sketaful** [blaxxun-boop/TargetPortal#51]
It have happened a few times now that showing the portals on the map have stopped working. No portal shows on minimap, regular map or the actual portal map.

Before this have just been a bug that lasted like 30 seconds so I never really cared much. One time it did show new portals until I brought up the map and hid, showed the pins, then it showed.

But now. It didn't show, I couldn't teleport anywhere because there was no portals on the map. Waited and refreshed and all but didn't help.

Only thing in the log I could find was:
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TargetPortal.Map.AddPortalPins () (at <6f85d536a6d94817a96f1e95ba0ddcdc>:0)
TargetPortal.Map+RefereshPortalPins+<<Prefix>g__Update|0_0>d.MoveNext () (at <6f85d536a6d94817a96f1e95ba0ddcdc>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <be2cce08ca774b9684099a81093ecac0>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
TargetPortal.RefereshPortalPins:Prefix(Minimap)
Minimap:DMD<Minimap::Awake>(Minimap)
UnityEngine.GameObject:SetActive(GameObject, Boolean)
SetActiveOnAwake:Awake()`

**Comment by blaxxun-boop** [comment]
Please always share the BepInEx log. Not much people can do to help you without it.
