### ISSUE TITLE
Map question

### ISSUE THREAD

**Issue by n4tur3502** [blaxxun-boop/TargetPortal#6]
Hello, I was wondering if it would be possible to get a version of this without the map popping up? Like just name the portal and have it connect but only be accessible by whoever the permissions are set for?  I would try to edit the mod myself but dont know how to remove that function. Any help you could provide would be amazing. Thank you for your work.

**Comment by n4tur3502** [comment]
I figured it out. Was pretty easy once I actually read the code. Thank you again for your work.

**Comment by blaxxun-boop** [comment]
@n4tur3502 Please be aware that "no license" means you aren't really allowed to modify the code. No one will say anything, if you make small changes and then use the modified mod just for yourself, obviously, but you can get in huge trouble, if you then go ahead and share the modified mod with someone else.

The best way would be, to simply create a pull request with your changes. That way, everyone gets to enjoy your changes as well.

**Comment by n4tur3502** [comment]
I have zero plans on publishing anything or sharing someone else's hard work. I mostly just wanted to remove the map pop up and I doubt I did it in a proper way lol. I am just learning at the moment but will absolutely do a pull request if I plan on actually sharing. Apologies for anything I'm doing wrong and thank you for the help.
