### ISSUE TITLE
Portals dont show up in the map if you restart the game.

### ISSUE THREAD

**Issue by TyberiousNWK** [blaxxun-boop/TargetPortal#8]
love the interface of the mod but when we restart the server (we are playing on a dedicated server) we lose all portal locations not in our immediate vicinity.

**Comment by blaxxun-boop** [comment]
Are you using BetterNetworking? I know that this mod can cause issues like this.

**Comment by TyberiousNWK** [comment]
[image: image.png][image: image.png]
Were not using better networking, but this is our entire mod list. Thank
you for your time.

**Comment by TyberiousNWK** [comment]
![Screenshot 2022-12-03 140818](https://user-images.githubusercontent.com/119559210/205459942-47110808-ff5c-433c-b4ff-a2d4c943f58c.png)
![Screenshot 2022-12-03 140843](https://user-images.githubusercontent.com/119559210/205459948-ed1c1f85-b56b-4b29-ace5-f1a41b3ce4d9.png)

**Comment by TyberiousNWK** [comment]
oh i apologize i skipped item drawers by makail between those two
screenshots, scrolled too fast haha.

**Comment by blaxxun-boop** [comment]
So, I've tested this for well over 2 hours now and no matter what I do, the portals are always there and everything works fine. It's probably an incompatibility with another map mod.

**Comment by blaxxun-boop** [comment]
P.S.: I just looked at the code of the MapSync mod you are using and it seems to manipulate map pins. Might be removing the TargetPortal pins from the map.

**Comment by TyberiousNWK** [comment]
oh okay thank you i will stop using that one. would much rather have this portal mod.

**Comment by Hoogie1980** [comment]
Any insight to which mod was causing this?  I am having this same problem now.

**Comment by TyberiousNWK** [comment]
for me it was the MapSync Mod by nashy because it edited the same file i think, i took it off and it was immediately fixed

**Comment by TyberiousNWK** [comment]
> Any insight to which mod was causing this? I am having this same problem now.

for me it was the MapSync Mod by nashy because it edited the same file i think, i took it off and it was immediately fixed

**Comment by TyberiousNWK** [comment]
basically any Map mod is gonna make this issue happen in *my* testing.
