### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by mook06** [blaxxun-boop/TargetPortal#9]
Any chance gamepad support could be added? thanks

**Comment by cbdejavu** [comment]
Gamepad support would make this the perfect portal mod for what I'm looking for however, unfortunately without gamepad support makes it kind of useless for my personal use case but I absolutely love the app (and the lack of dependency on jotunn library).

I don't know that much about modding for valheim but if the selection of the portal could be setup in the configuration to be changeable from the left mouse click to something on the gamepad it would be awesome.  Hopefully it is something you consider.

**Comment by blaxxun-boop** [comment]
Not going to happen, sorry. Someone asked about gamepad support for my mods and I've looked into it. The vanilla game barely works with gamepad. Adding support for mods is a huge pain in the ass and would probably take a week. And there are less than 2% of players using a gamepad, so it's really not worth it.
